version: '3.8'

services:
  localstack:
    image: localstack/localstack:3.0
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - EDGE_PORT=4566
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./init:/etc/localstack/init/ready.d
      - localstack-data:/var/lib/localstack

volumes:
  localstack-data:
