apiVersion: v1
kind: Namespace
metadata:
  name: fiap
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-hct-not-csm-dep
  namespace: fiap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-hct-not-csm
  template:
    metadata:
      labels:
        app: app-hct-not-csm
    spec:
      containers:
        - name: app-hct-not-csm
          image: 913524932573.dkr.ecr.us-east-1.amazonaws.com/notification_repo:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "1"
              memory: "2Gi"
          env:
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
            - name: AWS_REGION
              value: "us-east-1"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secret-access-key
            - name: DYNAMO_DB_ENDPOINT
              value: "https://dynamodb.us-east-1.amazonaws.com"
            - name: SQS_ENDPOINT
              value: "https://sqs.us-east-1.amazonaws.com"
            - name: SQS_NOTIFICATION_QUEUE
              value: "notification-event-queue"
            - name: S3_ENDPOINT
              value: "https://bucket-fiap-hackaton-t32-files.s3.us-east-1.amazonaws.com/uploads"
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: sendgrid-api-key
            - name: SENDGRID_FROM_EMAIL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: sendgrid-from-email
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: fiap
type: Opaque
data:
  access-key-id: QUtJQTVKTVNVSDdPVFROUlhIVVo=
  secret-access-key: RzJKbWt0RjRFNTdFaUg3bzBXV1d6cnd3d0U5Y3ZtbTEveWhOZzBvag==
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: fiap
type: Opaque
data:
  sendgrid-api-key: U0cuVWxueHUzNkpRbVd6Q3lUeHRlenlKdy5TSHJGdTNheHZBRnZfd0NOTlRBeWl1eEJyanA3WTI3WF9ycjBzVGRrMm9F
  sendgrid-from-email: amVhbi5jYXJsb3NANWx5NS5jb20uYnI=
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-aws-credentials
  namespace: fiap
spec:
  secretTargetRef:
    - parameter: accessKeyID
      name: aws-credentials
      key: access-key-id
    - parameter: secretAccessKey
      name: aws-credentials
      key: secret-access-key
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: aws-sqs-scaledobject
  namespace: fiap
spec:
  scaleTargetRef:
    name: app-hct-not-csm-dep
  minReplicaCount: 1
  maxReplicaCount: 10
  pollingInterval: 30
  cooldownPeriod: 300
  triggers:
    - type: aws-sqs-queue
      metadata:
        queueURL: https://sqs.us-east-1.amazonaws.com/913524932573/notification-event-queue
        queueLength: "5"
        awsRegion: us-east-1
      authenticationRef:
        name: keda-aws-credentials