aws:
  sqs:
    queue-url: http://localhost:4566/000000000000/email-queue
    region: us-east-1
  credentials:
    access-key: test
    secret-key: test

sendgrid:
  api-key: ${SENDGRID_API_KEY}
  from-email: notificacoes@seudominio.com

spring:
  main:
    allow-bean-definition-overriding: true
