spring:
  application:
    name: notification-consumer

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ${AWS_REGION}
      sqs:
        endpoint: ${SQS_ENDPOINT}
      dynamodb:
        endpoint: ${DYNAMO_DB_ENDPOINT}
        table-prefix: fiap-hackaton-
app:
  message-broker:
    event:
      notification:
        queue-name: notification-event-queue
sendgrid:
  api-key: ${SENDGRID_API_KEY}
  email:
    from: ${SENDGRID_FROM_EMAIL}
