spring:
  application:
    name: notification-consumer
  profiles:
    active: local

  cloud:
    aws:
      sqs:
        region: ${AWS_REGION:us-east-1}
        endpoint: ${SQS_ENDPOINT:http://localhost:4566}
      dynamodb:
        region: ${AWS_REGION:us-east-1}
        endpoint: ${DYNAMO_DB_ENDPOINT:https://localhost.localstack.cloud:4566}
        table-prefix: fiap-hackaton-

app:
  message-broker:
    event:
      notification:
        queue-name: notification-event-queue
sendgrid:
  api-key: ${SENDGRID_API_KEY}
  from-email: ${SENDGRID_FROM_EMAIL}
